version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - abruere
  labels:
  - "type: Dependencies"
  ignore:
  - dependency-name: intl-messageformat-parser
    versions:
    - "> 2.1.3"
  - dependency-name: mapbox-gl
    versions:
    - ">= 2.a, < 3"
  - dependency-name: socket.io-client
    versions:
    - ">= 3.a, < 4"
  - dependency-name: vuelidate
    versions:
    - "> 0.7.4"
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: vue-intl
    versions:
    - 4.1.10
    - 4.1.12
    - 4.1.14
    - 4.1.15
    - 4.1.17
    - 4.1.22
    - 4.1.24
    - 4.1.26
    - 4.1.27
    - 4.1.4
    - 4.1.7
    - 4.1.8
  - dependency-name: socket.io-client
    versions:
    - 4.0.0
  - dependency-name: quasar
    versions:
    - 1.15.1
    - 1.15.2
    - 1.15.3
    - 1.15.4
    - 1.15.5
    - 1.15.7
    - 1.15.9
  - dependency-name: "@quasar/app"
    versions:
    - 2.2.3
  - dependency-name: html-loader
    versions:
    - 2.0.0
    - 2.1.0
    - 2.1.1
  - dependency-name: vue-tel-input
    versions:
    - 5.0.3
    - 5.0.4
    - 5.1.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
